using System.Collections.Generic;
using MaplePet.Engine;

namespace MaplePet.Api.Hub;

/// <summary>The hub "database": the registry the app downloads from the CDN (<c>index.json</c>), holding one
/// <see cref="HubEntry"/> per published command. Generated by the hub repo's CI from each command's
/// <c>command.md</c> + <c>hub.meta.json</c>; the app only reads it.</summary>
public sealed class HubIndex
{
    public int SchemaVersion { get; set; }
    public string? IndexTag { get; set; }
    public string? GeneratedAt { get; set; }
    public List<HubEntry> Commands { get; set; } = new();
}

/// <summary>One published command in the hub registry. Identity is <see cref="Id"/> (the stable slug, ==
/// folder name in the hub repo). Everything here is for discovery + the pre-install disclosure; the actual
/// command bytes live in the <see cref="Download"/> zip, verified against <see cref="HubDownload.Sha256"/>.</summary>
public sealed class HubEntry
{
    public string Id { get; set; } = "";              // slug / primary key
    public string Name { get; set; } = "";            // invoke word (no leading '/')
    public string Title { get; set; } = "";           // human display title
    public string Version { get; set; } = "1.0.0";    // semver of this command
    public string Author { get; set; } = "";          // verified GitHub login
    public string License { get; set; } = "";
    public string Description { get; set; } = "";
    public string Kind { get; set; } = "";            // text|clipboard|image|link|prompt|pet|script
    public List<string> Tags { get; set; } = new();
    public string? MinAppVersion { get; set; }        // null = no minimum
    public bool RequiresScripting { get; set; }       // kind == script
    public bool RequiresNetwork { get; set; }         // declares hosts:
    public bool RequiresChat { get; set; }            // kind == prompt
    public List<string> Hosts { get; set; } = new();  // declared network allowlist, for disclosure
    public bool Official { get; set; }
    public bool Verified { get; set; }
    public string? Updated { get; set; }              // ISO-8601, display only
    public string? RepoPath { get; set; }             // for "view source on GitHub"
    public HubDownload Download { get; set; } = new();
}

/// <summary>Where to fetch a command's install-ready zip and how to verify it.</summary>
public sealed class HubDownload
{
    public string Url { get; set; } = "";
    public long Bytes { get; set; }
    public string Sha256 { get; set; } = "";          // the integrity anchor; verified before extract
    public string? FallbackUrl { get; set; }          // tried if the primary URL fails transport
}

/// <summary>The result of an install/update attempt, surfaced to the UI status line.</summary>
public sealed record InstallResult(bool Ok, string Message, CommandEntry? Entry = null);
